import { FormEvent, useEffect, useState } from 'react';

const api = import.meta.env.VITE_API_URL || 'http://localhost:8080/api';
type Release = { id:number; name:string; targetDate:string; status:string };
type Dashboard = { releaseName:string; decision:'GO'|'NO_GO'; reasons:string[]; requirements:number; requirementsWithTests:number; testCases:number; testRuns:number; passedRuns:number; failedRuns:number; openDefects:number; openBlockers:number; passRate:number };
export default function App() {
  const [releases, setReleases] = useState<Release[]>([]); const [selected, setSelected] = useState<number>(); const [dashboard, setDashboard] = useState<Dashboard>(); const [error, setError] = useState('');
  const load = async () => { try { const data=await (await fetch(`${api}/releases`)).json(); setReleases(data); if (!selected && data[0]) setSelected(data[0].id); } catch { setError('Cannot reach the API. Start the backend on port 8080.'); } };
  useEffect(()=>{load();},[]); useEffect(()=>{ if (selected) fetch(`${api}/releases/${selected}/dashboard`).then(r=>r.json()).then(setDashboard).catch(()=>setError('Unable to load dashboard.')); },[selected]);
  const createRelease = async (event:FormEvent<HTMLFormElement>) => { event.preventDefault(); const form=new FormData(event.currentTarget); const r=await fetch(`${api}/releases`, {method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:form.get('name'),targetDate:form.get('targetDate')})}); if (!r.ok) return setError('Release could not be created.'); const created=await r.json(); setReleases([...releases,created]); setSelected(created.id); event.currentTarget.reset(); };
  return <main><header><p className="eyebrow">RELEASE QUALITY WORKSPACE</p><h1>ReleasePilot</h1><p>Evidence-based readiness for every release.</p></header><section className="toolbar"><label>Release<select value={selected ?? ''} onChange={e=>setSelected(Number(e.target.value))}>{releases.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label><form onSubmit={createRelease}><input name="name" placeholder="New release name" required/><input name="targetDate" type="date" required/><button>Create release</button></form></section>{error && <p className="error">{error}</p>}{dashboard && <><section className={`decision ${dashboard.decision === 'GO' ? 'go' : 'no-go'}`}><div><span>RELEASE DECISION</span><strong>{dashboard.decision === 'GO' ? 'GO' : 'NO-GO'}</strong></div><ul>{dashboard.reasons.map(reason=><li key={reason}>{reason}</li>)}</ul></section><section className="metrics"><Metric label="Requirements" value={`${dashboard.requirementsWithTests}/${dashboard.requirements}`}/><Metric label="Test cases" value={dashboard.testCases}/><Metric label="Pass rate" value={`${dashboard.passRate}%`}/><Metric label="Open defects" value={dashboard.openDefects}/><Metric label="Blockers" value={dashboard.openBlockers}/><Metric label="Failed runs" value={dashboard.failedRuns}/></section><section className="card"><h2>How this demo works</h2><p>The seeded ShopSphere checkout release intentionally contains one failed UI test and an open blocker defect. Use the REST API to add requirements, test cases, runs, and defects; refresh this dashboard to see the release decision update.</p></section></>}</main>;
}
function Metric({label,value}:{label:string;value:string|number}) { return <article><span>{label}</span><strong>{value}</strong></article>; }
